version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
    environment:
      - SERVICES=sqs,sns,events
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  sqs-admin-ui:
    container_name: sqs_admin_ui
    image: akilamaxi/sqs-admin-ui:v1
    environment:
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_REGION=eu-west-2
      - SQS_ENDPOINT_URL=http://localstack:4566 
    ports:
      - "8080:8080"
    depends_on:
      - localstack